services:
  artel:
    build: .
    volumes:
      - artel-data:/data
      - ./artel:/app/artel

  archivist:
    build: .
    volumes:
      - artel-data:/data
      - ./artel:/app/artel
    environment:
      - DB_PATH=/data/artel.db

  mdns:
    build: .
    volumes:
      - ./artel:/app/artel

  watchtower:
    profiles:
      - production
